# Generated by Django 4.1.2 on 2022-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('propietario', models.CharField(max_length=30)),
                ('especie', models.CharField(max_length=10)),
                ('raza', models.CharField(max_length=15)),
            ],
        ),
    ]
